version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: trustmark

    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  springboot-app:
    build: .
    depends_on:
      - mysql
    ports:
      - "80:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/trustmark
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
